steps:
  - name: ":classical_building: Building docker image"
    command: "docker build -f Dockerfile.dev . -t pratikbhumkar/create-invoice-tool-dev"
  - wait
  - name: ":lint-roller: Checking for lints"
    command: "docker run pratikbhumkar/create-invoice-tool-dev npm run lint"
  - wait
  - name: ":lint-roller: Testing code"
    command: "docker run pratikbhumkar/create-invoice-tool-dev npm test"
  - block: ":rocket: Run local build!"
  - name: ":classical_building: Building local image"
    command: "docker build -f Dockerfile . -t pratikbhumkar/create-invoice-tool"
  - wait
  - name: ":surfer: Running local image"
    command: "docker run -p 4000:4000 -d pratikbhumkar/create-invoice-tool"
  - block: ":rocket: Release to production!"
  - name: ":classical_building: Building image for heroku"
    command: "docker build -t registry.heroku.com/thawing-bayou-98812/web ."
  - wait
  - name: ":surfer: pushing image to heroku"
    command: "docker push registry.heroku.com/thawing-bayou-98812/web"
  - wait
  - name: "Set Heroku config/environment variables"
    commands:
      # - "heroku config:set PORT={{$PORT}} -a thawing-bayou-98812"
      - "heroku config:set MONGO_USERNAME=$MONGO_USERNAME -a thawing-bayou-98812"
      - "heroku config:set MONGO_PASSWORD=$MONGO_PASSWORD -a thawing-bayou-98812"
      - "heroku config:set AUDIENCE=$AUDIENCE -a thawing-bayou-98812"
      - "heroku config:set AUTH0_DOMAIN=$AUTH0_DOMAIN -a thawing-bayou-98812"
  - wait
  - name: ":surfer: release app from heroku"
    command: "heroku container:release web -a thawing-bayou-98812"
