steps:
  - name: ":classical_building: Building image for heroku"
    command: "docker build -t registry.heroku.com/thawing-bayou-98812/web ."
  - wait
  - name: ":lint-roller: Checking for lints"
    command: "docker run registry.heroku.com/thawing-bayou-98812/web npm run lint"
  - wait
  - name: ":surfer: pushing image to heroku"
    command: "docker push registry.heroku.com/create-invoice-tool/web"
  - wait
  - name: ":surfer: release app from heroku"
    command: "heroku container:release web -a thawing-bayou-98812"
  - block: ":rocket: Release to docker repo!"
  - name: ":classical_building: Building docker image"
    command: "docker build . -t pratikbhumkar/create-invoice-tool"
  - wait
  - name: ":lint-roller: Checking for lints"
    command: "docker run docker.io/pratikbhumkar/create-invoice-tool npm run lint"
  - wait
  - name: ":shipit: Shipping docker image"
    command: "docker push pratikbhumkar/create-invoice-tool"
  - wait
  - name: ":surfer: Running image"
    command: "docker run -p 4000:4000 -d pratikbhumkar/create-invoice-tool"